---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey


# Basic Site Settings
title: msaul/homepage
language: en
#color: grey
target: _self
headerStyle: boxed
hideVersion: true
disableCollapse: false
useEqualHeights: false
showStats: false
statusStyle: "."

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  hideVisitURL: false
  provider: google

# Site Assets
#base: http://localhost:3000
#favicon: /icons/favicon-small.png
background: /images/background.png




# Layout Configuration
layout:
  Homelab:
    style: row
    columns: 2
    header: false
    useEqualHeights: true
    showStats: true
    cardBlur: md
  Productivity:
    style: row
    columns: 2
    header: false
    useEqualHeights: true
    cardBlur: md
  ARR Suite:
    style: column
    header: false
    cardBlur: md
  Frontend Media Servers:
    style: column
    header: false
    cardBlur: md
  Media Tools:
    style: column
    header: false
    cardBlur: md
  Download Clients:
    style: column
    header: false
    cardBlur: md
  Other Services:
    style: column
    header: false
    cardBlur: md
  AI & Development:
    style: column
    header: false
    cardBlur: md
  Infrastructure:
    style: column
    header: false
    cardBlur: md
  


#    iconsOnly: true